-- V1: accounts and saved analyses.
--
-- Both tables land in ONE migration although the login itself ships in F-03. `analyses` belongs to a
-- user from its first row, so creating `users` here avoids the compensating migration that would
-- otherwise have to add a NOT NULL foreign key to a table that already holds rows nobody owns.
--
-- Every type below is chosen to mean the same thing to PostgreSQL and to H2 in PostgreSQL
-- compatibility mode, because one migration set serves both. `SERIAL`, `jsonb`, `citext` and
-- `TIMESTAMPTZ` are not — hence identity columns, TEXT, and TIMESTAMP WITH TIME ZONE spelled out.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- The email IS the login, so uniqueness is a database constraint rather than a check the
-- registration endpoint might forget under a race. The application lower-cases before writing
-- (UserAccount.create), because a case-insensitive index would need Postgres-only citext or a
-- functional index H2 does not mirror — so the normalisation is code, and the constraint is schema.
CREATE UNIQUE INDEX ux_users_email ON users (email);

CREATE TABLE analyses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    -- title and note are the only columns a user edits after saving; they exist so the required
    -- update operation has an honest subject. An analysis itself is a record of what the model said
    -- at a point in time and must not be editable, or the saved verdict stops being evidence.
    title           VARCHAR(200) NOT NULL,
    note            VARCHAR(2000),
    source_url      VARCHAR(2048),
    -- Denormalised summary of the payload, so the saved-list view renders without deserialising
    -- every row. Nullable because extraction can legitimately fail to find any of them.
    make            VARCHAR(100),
    model           VARCHAR(100),
    production_year INTEGER,
    price_amount    NUMERIC(12, 2),
    price_currency  VARCHAR(8),
    mileage_km      INTEGER,
    verdict_code    VARCHAR(40),
    overall_score   INTEGER,
    -- The whole AnalysisResponse as JSON. Normalising ~40 nested fields across six tables buys
    -- queries this application does not make; the summary columns above cover everything it lists,
    -- sorts or filters on. TEXT rather than jsonb because jsonb has no H2 equivalent.
    payload         TEXT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_analyses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- The one query the list view makes: this user's saved analyses, newest first.
CREATE INDEX ix_analyses_user_created ON analyses (user_id, created_at DESC);
